### ISSUE TITLE
Simplified Chinese or traditional Chinese?

### ISSUE THREAD

**Issue by yanshao9798** [UniversalDependencies/UD_Chinese#1]
Hi! I am wondering why is the UD Chinese treebank in traditional Chinese whereas in README it says "Simplified Chinese Universal Dependencies Treebank annotated and converted by
Google" ? Is there also a simplified Chinese version available?

**Comment by ermanh** [comment]
You're right, the data is entirely in traditional characters -- the README title has been updated. (As for a simplified version, you could try a traditional-to-simplified converter, such as the Python module `mafan`).

**Comment by dan-zeman** [comment]
I have now updated the README file in the dev branch.
